name: 'k8s helm deploy'
description: 'use helm to deploy to k8s'
inputs: 
  PROJECT: 
    required: true
  APP:
    required: true
  INSTANCE:
    required: true
  REPOSITORY:
    required: false
  DOCKER_USER: 
    required: true
    default: "builder"
  DOCKER_PASS:
    required: false
  PROJECT_VALUES:
    required: false
    default: ".github/helm/values-project.yml"    
  INSTANCE_VALUES:
    required: false
    default: ".github/helm/values-insance.yml"  
runs:
  using: 'docker'
  image: 'Dockerfile'
